query GetVaultTransactions {
  transactions(
    first: 10
    orderBy: Timestamp
    orderDirection: Desc
    where: { vaultAddress_in: ["0xDCd35A430895cc8961ea0F5B42348609114a9d0c"] }
  ) {
    items {
      blockNumber
      hash
      type
      user {
        address
      }
      timestamp
    }
  }
}
