query GetVaultDisplay {
  vaultByAddress(
    address: "0xDDD64e2EF73b0741BdB1e2813a1115FD150aef36"
    chainId: 8453
  ) {
    whitelisted
    name
    address
    symbol
    liquidity {
      underlying
      usd
    }
    asset {
      address
      symbol
      name
      decimals
      priceUsd
      tags
      logoURI
      chain {
        id
      }
    }
    metadata {
      description
      image
      curators {
        image
        name
      }
    }
    state {
      allocation {
        supplyAssets
        supplyAssetsUsd
        market {
          uniqueKey
          collateralAsset {
            address
            symbol
            name
            decimals
            priceUsd
            tags
            logoURI
            chain {
              id
            }
          }
        }
      }
      apy
      netApy
      weeklyNetApy
      monthlyNetApy
    }
    allocators {
      address
    }
    chain {
      id
      network
    }
    creationBlockNumber
    creationTimestamp
    creatorAddress
    factory {
      address
    }
  }
}
