query GetVaultTransactions {
  transactions(
    first: 10
    orderBy: Timestamp
    orderDirection: Desc
    where: { vaultAddress_in: ["0x4DC97f968B0Ba4Edd32D1b9B8Aaf54776c134d42"] }
  ) {
    items {
      blockNumber
      hash
      type
      user {
        address
      }
      timestamp
    }
  }
}
