query GetVaultTransactions {
  transactions(
    first: 10
    orderBy: Timestamp
    orderDirection: Desc
    where: { vaultAddress_in: ["0xDDD64e2EF73b0741BdB1e2813a1115FD150aef36"] }
  ) {
    items {
      blockNumber
      hash
      type
      user {
        address
      }
      timestamp
    }
  }
}
